project:
  name: LineUp
  version: 0.0.1
  github_maintainer: gabrielfalcao
  description: Distributed pipeline framework for python
  github_url: http://github.com/gabrielfalcao/lineup
  tarball_download_url: https://github.com/gabrielfalcao/lineup/archive/master.tar.gz

documentation:
  index: introduction.md
