project:
  name: LineUp
  version: 0.1.7
  github_maintainer: weedlabs
  description: Distributed pipeline framework for python
  github_url: http://github.com/weedlabs/lineup
  tarball_download_url: https://github.com/weedlabs/lineup/archive/master.tar.gz

documentation:
  index: intro.md

toc:
  - intro.md
  - getting-started.md
  - how-to-cli.md
  - how-to-steps.md
